### PR TITLE
fix: enabled fuzzing

### PR DESCRIPTION
**Pull request by ezhil56x**
/claim #163 

- Added a job named cargo-fuzz to fuzz

### CODE REVIEW

**Comment by koraa** [comment]
@ezhil56x Please reset your branch to https://github.com/rosenpass/rosenpass/pull/186

**Comment by koraa** [comment]
OK whatever. I merged your changes via #186 and asked a contact at algoria how to payout your bounty…

**Comment by ezhil56x** [comment]
> OK whatever. I merged your changes via #186 and asked a contact at algoria how to payout your bounty…

I think only when this PR is merged I will get a bounty

**Comment by koraa** [comment]
Lets pay it out through a tip, so this is done :)

**Comment by ezhil56x** [comment]
> Lets pay it out through a tip, so this is done :)

Is it done?

**Comment by koraa** [comment]
Your code was merged and landed in the main branch; I had to merge it manually since it needed to be rebased: https://github.com/rosenpass/rosenpass/commit/284ebb261f1b0c14e0dd120fba4e032a9e787eef

**Comment by ezhil56x** [comment]
> Your code was merged and landed in the main branch; I had to merge it manually since it needed to be rebased: [284ebb2](https://github.com/rosenpass/rosenpass/commit/284ebb261f1b0c14e0dd120fba4e032a9e787eef)

`/tip` is not triggered I guess

**Pull request closed without merging**
