### PR TITLE
Add .devcontainer configuration

### PR DESCRIPTION
**Pull request by mogery**
This PR sets up a `.devcontaner` configuration to enable the use of any tools built on devcontainers in development. It sets the dev environment up based on the repo's `flake.nix`, using the [`nix-devcontainer`](https://github.com/xtruder/nix-devcontainer) project.

### CODE REVIEW

**Comment by koraa** [comment]
@mogery This is basically a config for a specific tool some devs might use but does not have an impact on anybody else?

**Comment by thaodt** [comment]
> @mogery This is basically a config for a specific tool some devs might use but does not have an impact on anybody else?

yeah, i guess so. The `.devcontainer` will be used by VSCode

**Comment by mogery** [comment]
> @mogery This is basically a config for a specific tool some devs might use but does not have an impact on anybody else?

Yup. Also enables using GitHub Workspaces.

**Comment by koraa** [comment]
> > @mogery This is basically a config for a specific tool some devs might use but does not have an impact on anybody else?
> 
> Yup. Also enables using GitHub Workspaces.

Cool. Happy to merge it when the CI is passing.

**Comment by mogery** [comment]
@koraa Should pass now.

**Comment by mogery** [comment]
> Merging master back into a feature branch is kind of a bad practice IMO. Squashing and merging.
> 
> @mogery Good work!
> 
> /tip 20

Thanks! Good to know.

The default on the GitHub UI is the merge commit method.

Screenshot 2024-04-19 at 15 56 20

I think there may be a way to configure this. I'll look into it.

**Comment by koraa** [comment]
@mogery Sorry for the delay, we went through our open bounties to pay today :grimacing:

**Comment by mogery** [comment]
Heh, all good, thanks! Completely forgot about that bounty, a pleasant surprise :)

**Pull request merged**
