### PR TITLE
Alice/doc upload

### PR DESCRIPTION
**Pull request by AliceOrunitia**
Created an implementation of an automated documentation uploader and compiler that should automatically compile files, using mandoc, into the rosenpass-website repo at /static/docs every time a change is made to rosenpass at /doc.

As this necessitated changes to both the rosenpass-website and rosenpass repo, I will copy the same changes to both pull requests:

1- added a menu item for documentation in the config file with a weight of 20
2- added a button in the “getting started” section for documentation.
3- created a “docs” directory under “/static”, where all documentation files will be stored.
4- created a shortcodes file called “htmlfile.html” to allow documentation to be printed
5- in the documentation.md file, created headers for current docs, if entirely new files are added, then new headers must be generated
6- created a new block shortcode for different documents within the webpage, need to polish layout
7- produced a doc-upload.yml file to automate the process of updating or creating new documentation files via mandoc compilation, embedded within rosenpass. Requires both an access key and for github actions to be allowed to read/write. This code will not run until those are provided. Current code assumes that the added secret will be named "PRIVACC".
8- created some custom CSS to handle the behaviour of the documentation buttons within the documentation page, with a view to eventually adding more buttons at a later date if more files are added.

### CODE REVIEW

**Comment by koraa** [comment]
Great! Could you please start by using an [interactive rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) to combine your commits into something more managable with a readable commit message?

**Comment by koraa** [comment]
(Make a backup of your local copy though just to be sure nothing bad happens)

**Comment by koraa** [comment]
Oh. And. Thank you for this contribution!!! :1st_place_medal:

**Comment by AliceOrunitia** [comment]
All fixed! (I hope)

**Comment by wucke13** [comment]
@AliceOrunitia Thank you for the contribution! From my standpoint, this looks good for merge! I'd however ask @emilengler to once look over this, IIRC he is quite familiar with mandoc.

**Comment by emilengler** [comment]
> @AliceOrunitia Thank you for the contribution! From my standpoint, this looks good for merge! I'd however ask @emilengler to once look over this, IIRC he is quite familiar with mandoc.

The invocation of `mandoc(1)` looks good to me. I cannot really comment on the others parts.

**Review by wucke13 — APPROVED** [review]

**Pull request merged**
