### PR TITLE
feat: Move dependencies into the workspace

### LINKED ISSUE #178: Move dependencies into the workspace
https://github.com/rust-lang/cargo/issues/8415

/bounty 10

### PR DESCRIPTION
**Pull request by jemiluv8**
Move external dependencies to the workspace cargo.toml file
/claim #178 
fixes #178

### CODE REVIEW

**Comment by koraa** [comment]
@jemiluv8 Nice. Thank you for the contribution! Please also manage the locations of the workspace binaries as well as the selected features centrally.

**Comment by koraa** [comment]
Sorry, I have been unclear in my previous request; can you also move the paths to the workspace *crates* (sorry) to the central one? I believe we can merge after that…

**Comment by jemiluv8** [comment]
Ok. I think I get it now.

**Comment by koraa** [comment]
Splendid. Thank you!

**Pull request merged**
