### PR TITLE
add version command #105

### PR DESCRIPTION
**Pull request by lamr02n**
I added a version command for rosenpass that shows the current version.

See #105

### CODE REVIEW

**Comment by emilengler** [comment]
I am against this. There is also `-V` and `--version`, due to `clap`.

**Comment by emilengler** [comment]
I was not aware of this, thank you for letting me know.

@koraa I will give this to you then. Sorry for closing #105 already

**Comment by koraa** [comment]
> I am against this. There is also `-V` and `--version`, due to `clap`.

Please elaborate on the point!

> This task was given to me by @koraa to show my ability to contribute to the project which we discussed in a meeting today. If it is fine for her, publishing the change is not necessary.

Yes, but this is no reason to discard @emilengler or not follow the normal PR procedure :D 

Anyway, glad you where able to create the patch so quickly.

**Comment by emilengler** [comment]
> Please elaborate on the point!

`rosenpass -V` and `rosenpass --version` already provide the desired behavior and at least the latter option is well-established.

**Comment by koraa** [comment]
@lamr02n You just met emil who will be able to help you a bit in your performance measurement project. He clearly knows more about this software than I!

Sorry for not properly vetting the issue before asking you to work on it. You did a great job.

I've invited you to the crew GH team; please go ahead, close the issue that motivated this PR explaining why we reject it.

And join the IRC please so I can properly introduce you to everyone!

**Comment by lamr02n** [comment]
I am pleased to meet you, @emilengler, and looking forward to work on the performance measurement project.

@koraa Working on the issue was a fun way of getting to know the software a little bit more. I have closed the issue explaining our reasons and joined the IRC.

**Comment by koraa** [comment]
> I am pleased to meet you, @emilengler, and looking forward to work on the performance measurement project.
> 
> @koraa Working on the issue was a fun way of getting to know the software a little bit more. I have closed the issue explaining our reasons and joined the IRC.

Wonderful!

**Comment by koraa** [comment]
@lamr02n I see you haven't managed to get on the Chat yet. Could you go ahead and do that please?

**Comment by koraa** [comment]
Oh and @lamr02n – given that you managed to create the version command –  would you be interested in looking at #109?

**Comment by lamr02n** [comment]
@koraa I can take a look at it and see if I can do something.

**Comment by koraa** [comment]
> @koraa I can take a look at it and see what I can do.

Wonderful!

**Pull request closed without merging**
