### PR TITLE
ci: Invoke the mandoc linter

### PR DESCRIPTION
**Pull request by emilengler**

### CODE REVIEW

**Comment by emilengler** [comment]
@wucke13 do we have to integrate this into nix?

**Comment by prabhpreet** [comment]
@emilengler Do you need any help with this issue?

**Comment by emilengler** [comment]
> @emilengler Do you need any help with this issue?

I forgot about this merge request. Go ahead and feel free to commit to this branch :)

**Comment by prabhpreet** [comment]
I tried- I don't think I had permissions. I tried out the workflow commands locally and they worked.

Can you grant me permissions? Otherwise, feel free to merge from main branch

**Comment by emilengler** [comment]
Hmmm, I cannot. Could you fork the branch and create a new PR? I would close this here and delete the old branch then.

**Comment by prabhpreet** [comment]
Done in #296

**Pull request closed without merging**
