### PR TITLE
feat(cli): Automatically generate man page

### PR DESCRIPTION
**Pull request by aparcar**
Instead of using a static one, generate it via clap_mangen

This is the *refactorless* version of #430 

This implementation does not depend on the upstream patch https://github.com/clap-rs/clap/pull/5769. However it can be updated once the patch is accepted without troubling downstream tooling.

```
    feat(cli): Automatically generate man page
    
    Instead of using a static one, generate it via clap_mangen. To generate
    the manpage run `rosenpass --generate-manpage <folder>`.
    
    Right now clap does not support flattening of generated manpages,
    meaning that each subcommand is explained in its own file. To add extra
    sections to the main file `rosenpass.1`, it's rewritten after the
    initial creation.
    
    Once clap support flattened Man pages, the `generate_to` call can be
    removed and all subcommand are added to the `rosenpass.1` file.
    
    This implementation allows downstream manpage generation to stay
    unchanged even after switching from multiple manpages to a flattened
    one.
```

### CODE REVIEW

**Comment by aparcar** [comment]
I added some patches to `clap_mangen` to have a flattened man page as well as allowing "custom" sections (i.e. "EXIT STATUS"). Below is an automatically rendered man page.

image

**Comment by aparcar** [comment]
I'm not sure why those Nix CI jobs fail, @wucke13 do you have an idea?

**Comment by aparcar** [comment]
@koraa should the same work happen for `rp`?

**Comment by wucke13** [comment]
> I'm not sure why those Nix CI jobs fail, @wucke13 do you have an idea?

Looking into it now. Seems to be a [shortcoming/bug of naersk](https://github.com/nix-community/naersk/issues/310). Maybe its time to remove naersk as a dependency alltogether, and instead to either use

[crane](https://github.com/ipetkov/crane) or to the nixpkgs' native [buildRustPackage](]https://nixos.org/manual/nixpkgs/stable/#compiling-rust-applications-with-cargo). I'd be slightly in favour of the latter; it is less performant (the native `buildRustPackage` does not cache the compilation of dependencies, changing one bit of input causes all dependencies to be recompiled), but more vanilla, better maintained and plays very well with nixpkgs cross compilation machinery (which woul allow us to remove quite some cruft from the `flake.nix`.

This is potentially relevant to the discussion over in #412 .

**Comment by aparcar** [comment]
This implementation should be fine now, once upstream merges https://github.com/clap-rs/clap/pull/5769 I'll adopt the manage creation accordingly.

After this is merged I'll also create upstream patches for Debian and Alpine to incorporate `--generate-manpage` - if possible.

**Comment by aparcar** [comment]
Attached is the current output of the main Man page `rosenpass.1` Once upstream approves the flattened Man page PR, all subcommands are explained in that file, too.

```
rosenpass(1)                General Commands Manual               rosenpass(1)

NAME
       rosenpass - Build post-quantum-secure VPNs with WireGuard!

SYNOPSIS
       rosenpass [--log-level] [-v|--verbose] [-q|--quiet] [--api-listen-path]
       [--api-listen-fd] [--api-stream-fd] [--psk-broker-path]
       [--psk-broker-fd] [-p|--psk-broker-spawn] [--generate-manpage]
       [--print-completions] [-h|--help] [-V|--version] [subcommands]

SUBCOMMANDS
       rosenpass-exchange-config(1)
              Start Rosenpass in server mode and carry on with the key
              exchange

       rosenpass-exchange(1)
              Start in daemon mode, performing key exchanges

       rosenpass-gen-config(1)
              Generate a demo config file

       rosenpass-gen-keys(1)
              Generate the keys mentioned in a configFile

       rosenpass-keygen(1)
              Deprecated - use gen-keys instead

       rosenpass-validate(1)
              Validate a configuration

       rosenpass-help(1)
              Print this message or the help of the given subcommand(s)

OPTIONS
       --log-level=LOG_LEVEL
              lowest log level to show – log messages at higher levels will be
              omitted

       -v, --verbose
              show verbose log output – sets log level to "debug"

       -q, --quiet
              show no log output – sets log level to "error"

       --api-listen-path=API_LISTEN_PATH
              Where in the file-system to create the unix socket the rosenpass
              API will be listening for connections on

       --api-listen-fd=API_LISTEN_FD
              When rosenpass is called from another process, the other process
              can open and bind the unix socket for the Rosenpass API to use
              themselves, passing it to this process. In Rust this can be
              achieved using the
              [command-fds](https://docs.rs/command-fds/latest/command_fds/)
              crate

       --api-stream-fd=API_STREAM_FD
              When rosenpass is called from another process, the other process
              can connect the unix socket for the API themselves, for instance
              using the `socketpair(2)` system call

       --psk-broker-path=PSK_BROKER_PATH
              path of the wireguard_psk broker socket to connect to

       --psk-broker-fd=PSK_BROKER_FD
              fd of the wireguard_spk broker socket to connect to

              when this command is called from another process, the other
              process can open and bind the Unix socket for the psk broker
              connection to use themselves, passing it to this process -- in
              Rust this can be achieved using the
              [command-fds](https://docs.rs/command-fds/latest/command_fds/)
              crate

       -p, --psk-broker-spawn
              spawn a psk broker locally using a socket pair

       --generate-manpage=out_dir
              Generate man page

       --print-completions=shell
              Generate completion file for a shell

              [possible values: bash, elvish, fish, powershell, zsh]

       -h, --help
              Print help (see a summary with '-h')

       -V, --version
              Print version

EXIT STATUS
       The rosenpass utility exits 0 on success, and >0 if an error occurs.

SEE ALSO
       rp(1), wg(1)

       Karolin Varner, Benjamin Lipp, Wanja Zaeske, and Lisa Schmidt,
       Rosenpass, https://rosenpass.eu/whitepaper.pdf, 2023.

STANDARDS
       This tool is the reference implementation of the Rosenpass protocol, as
       specified within the whitepaper referenced above.

AUTHORS
       Rosenpass was created by Karolin Varner, Benjamin Lipp, Wanja Zaeske,
       Marei Peischl, Stephan Ajuvo, and Lisa Schmidt.

BUGS
       The bugs are tracked at https://github.com/rosenpass/rosenpass/issues.

                              rosenpass 0.3.0-dev                 rosenpass(1)
```

**Comment by aparcar** [comment]
@blipp @koraa kindly requesting a review whenever time permits

**Review by koraa — APPROVED** [review]

**Pull request merged**
