### PR TITLE
docs: Correct protocol retransmission unit/vars

### PR DESCRIPTION
**Pull request by aparcar**
Those are seconds not ms, also it's BEGIN not BEG.

### CODE REVIEW

**Comment by aparcar** [comment]
@koraa RETRANSMIT_ABORT is actually nowhere used in the code. Should this be fixed or is the variable obsolete?

**Comment by aparcar** [comment]
I just added a patch to print the retransmission time and it works fine, I wonder if we should set the retransmission abort to a counter instead of a specific duration. We could just compare it with `ih.tx_count`?

**Comment by aparcar** [comment]
Also I'm wondering if the comment regarding the use of `rand` crate is still valid. The same seems to be used in `public.rs` without the comment.

**Review by koraa — APPROVED** [review]

**Comment by koraa** [comment]
@aparcar Which comment about the rand crate? Lets remove the retransmission abort value if its not being used…

**Comment by aparcar** [comment]
> @aparcar Which comment about the rand crate? 

https://github.com/rosenpass/rosenpass/blob/main/rosenpass/src/protocol/protocol.rs#L1476

> Lets remove the retransmission abort value if its not being used…

I'll add another commit

**Comment by aparcar** [comment]
I added all requested changes, please feel free to merge at your convenience

**Pull request merged**
