### PR TITLE
ci: add regression test for boot race condition

### PR DESCRIPTION
**Pull request by aparcar**
If two instances start up at the same time, they end up with different keys on both ends. Test this with different delays of 2 (working), 1 (flaky) and 0 (broken) seconds.

### CODE REVIEW

**Comment by aparcar** [comment]
Since this is a rare corner case it'll be handled with low priority.

An initial discussion about this bug suggested to compare the result of a final `InitConf` hash and if both server and client are in the middle of a handshake, take the hash that's *larger* (i.e. higher integer value). This would drop the *smaller* handshake if happening in parallel without giving either communication partner the ability to force their handshake to be preferred.

**Comment by koraa** [comment]
Can you check if there is some way to mark this as failure-expected so we can merge this for now?

**Comment by koraa** [comment]
(Rebased)

**Comment by aparcar** [comment]
> Can you check if there is some way to mark this as failure-expected so we can merge this for now?

Doesn't look like https://github.com/actions/runner/issues/2347#issuecomment-2301892819

I'd just leave it open for now?

**Comment by aparcar** [comment]
I changed it so the job itself doesn't fail but instead adds a warning.

Once the race condition is fixed, we can set it to `exit 1`.

From my side this is now ready to fly.

image

**Review by koraa — APPROVED** [review]

**Pull request merged**
