### PR TITLE
encode local keys in base64

### PR DESCRIPTION
**Pull request by aparcar**
Wireguard keys are always handled base64 encoded which makes it easier to share and move around. At least the local public key would be shared one way or another.

This breaks existing setups, however I wonder if long term a switch to base64 encoded keys would be best. I couldn't find any similar comment in the issues but maybe I missed something, if so please close this.

### CODE REVIEW

**Comment by koraa** [comment]
@aparcar Thank you for submitting this pull request. I think this works, but I am doubtful that this is a good idea. The public key is a  >100kB file; sharing this anywhere online via copy-paste is hard to conceive of…

**Comment by koraa** [comment]
I just tried pasting a key with this patch, but either github or firefox refuse…

**Comment by aparcar** [comment]
I'm mostly thinking that both the Wireguard key and the Wireguard PSK are stored base64 encoded so it would add some consistency for file handling. To have everything in a single file it would also be easier to handle if it's base64 encoded.

**Comment by koraa** [comment]
> I'm mostly thinking that both the Wireguard key and the Wireguard PSK are stored base64 encoded so it would add some consistency for file handling. To have everything in a single file it would also be easier to handle if it's base64 encoded.

How would you put everything in a single file?

./cc @wucke13 @emilengler @stv0g What to you think about this?

**Comment by emilengler** [comment]
I'm not a fan of having everything in a file. This would require interfacing applications to implement a parsing logic. While it is only a small overhead, I believe that it is an unnecessary one.

**Comment by koraa** [comment]
I would not mind ascii armor; there are situations where that could be useful. I would mind text files that explode most people's text editors.

In any case, using ascii armor should remain an optional off-by-default feature and we should not allow any data below or above the ascii armor…

**Comment by wucke13** [comment]
So far, we did not see conclusive argumentation to move away from binary files. Most notably however, the use of PEM for keys sounds interesting. Feel free to continue the discussion in favour/against in https://github.com/rosenpass/rosenpass/issues/121 up until then.

**Pull request closed without merging**
